files: '.*py$'
repos:
-   repo: local
    hooks:
      - id: black
        name: Black Formatter
        description: Run Black to format code
        entry: black
        language: python
          
      - id: flake8
        name: Flake8 Checker
        description: Run Flake8 to check code requirements
        entry: flake8
        language: python
